<?php
$this->element
    ->setAction($this->url(array(), 'basket_add', true))
    ->setMethod('post');
?>
<form class="form-inline" action="<?php echo $this->element->getAction(); ?>" method="<?php echo $this->element->getMethod(); ?>">
    <?= $this->element->quantity->setAttrib('class', 'form-control'); ?>
    <label class="" for="quantity"><?= $this->product->getUnitSymbol(); ?></label>

    <?= $this->element->productId; ?>
    <input type="submit" value="Dodaj do koszyka" class="btn btn-sm btn-default"/>
</form>