Produkty:
<table class="mainProductTable">
    <tr>
        <th>L.p.</th>
        <th>Nazwa</th>
        <th>Cena</th>
        <th></th>
    </tr>
<?php $i=1; ?>
<?php foreach($this->products as $product): ?>
    <tr class="productRow">
        <td><?= $i; ?></td>
        <td><?= $product->getName(); ?></td>
        <td><?= $product->getSellingPrice(); ?></td>
        <td></td>
    </tr>
    <?php $i++; ?>
<?php endforeach; ?>
</table>