<h1>Produkty</h1>
<table class="mainProductTable table">
    <thead>
        <tr>
            <th>L.p.</th>
            <th>Nazwa</th>
            <th>Cena</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php $i=1; ?>
    <?php foreach($this->products as $product): ?>
        <tr class="productRow">
            <td><?= $i; ?></td>
            <td><?= $product->getName(); ?></td>
            <td><?= $product->getCatalogPrice(); ?></td>
            <td>
                <?= $this->productForms[$product->getId()]
                    ->setAction($this->url(array(), 'basket_add', true))
                    ->setMethod('post')
                    ->setDecorators(array(array('ViewScript', array(
                    'viewScript' => 'forms/add.phtml',
                    'product'=> $product,
                )))); ?>
            </td>
        </tr>
        <?php $i++; ?>
    <?php endforeach; ?>
    </tbody>
</table>