services:
  command.dispatchers:
    - "@basket.add.command.dispatcher"

  command.dispatcher.identity_resolver:
    class: "Infrastructure\CommandDispatcher\IdentityResolver"

  command.dispatcher.identity_map:
    class: "Infrastructure\IdentityMap"
    arguments: ["@command.dispatcher.identity_resolver", "@command.dispatchers"]

  command.dispatcher:
    class : "Infrastructure\CommandDispatcher\ClassBased"
    arguments: ["@command.dispatcher.identity_map"]