OrmProduct:
  tableName: product
  columns:
    id: &PRIMARY
      type: string
      notnull: true
      primary: true
      length: 36 #UUID
    name:
      type: string
    catalog_price:
      type: decimal(10)
      scale: 2
    unit_id: &FOREIGN
      type: string
      length: 36
  relations:
    OrmUnit:
      local: unit_id
      foreign: id
      type: one

OrmUnit:
  tableName: unit
  columns:
    id:
      <<: *PRIMARY
    name:
      type: string
    symbol:
      type: string

OrmUnitConversion:
  tableName: unit_conversion
  columns:
    id:
      <<: *PRIMARY
    from_id:
      <<: *FOREIGN
    to_id:
      <<: *FOREIGN
    factor: float
  relations:
    OrmUnitFrom:
      class: OrmUnit
      local: from_id
      foreign: id
      type: one
    OrmUnitTo:
      class: OrmUnit
      local: from_id
      foreign: id
      type: one

OrmBasket:
  tableName: basket
  columns:
    id:
      <<: *PRIMARY
    session_id:
      type: string
      length: 64

OrmBasketProduct:
  tableName: basket_product
  columns:
    id:
      <<: *PRIMARY
    basket_id:
      <<: *FOREIGN
    product_id:
      <<: *FOREIGN
    unit_id:
      <<: *FOREIGN
    quantity:
      type: integer
  relations:
    OrmBasket:
      local: basket_id
      foreign: id
      type: one
    OrmProduct:
      local: product_id
      foreign: id
      type: one
    OrmUnit:
      local: unit_id
      foreign: id
      type: one