production:
  appnamespace: "Application"
  autoloaderNamespaces:
    - Orm
    - BaseOrm
  bootstrap:
    path: APPLICATION_PATH/Bootstrap.php
    class: "Bootstrap"
  includePaths:
    src: APPLICATION_PATH/src
    models: APPLICATION_PATH/models
    generated: APPLICATION_PATH/models/generated
  phpSettings:
    display_startup_errors: 0
    display_errors: 0
  resources:
    container:
      configPath: APPLICATION_PATH/configs
      configs:
        - services.yml
    doctrine:
      config:
        data_fixtures_path: APPLICATION_PATH/doctrine/fixtures
        migrations_path: APPLICATION_PATH/doctrine/migrations
        models_path: APPLICATION_PATH/models
        sql_path: APPLICATION_PATH/doctrine/sql
        yaml_schema_path: APPLICATION_PATH/doctrine/schema
      connections:
        db: "sqlite:APPLICATION_PATH/resources/db/cart.db"
    frontController:
      controllerDirectory: APPLICATION_PATH/controllers
      moduleDirectory: APPLICATION_PATH/modules
      params:
        displayExceptions: 0
    layout:
      layoutPath: "APPLICATION_PATH/layout/scripts"
    modules:
    routes:
      files:
        - "APPLICATION_PATH/configs/routes.yml"

staging:
  _extends: production

testing:
  _extends: production
  phpSettings:
    display_startup_errors: 1
    display_errors: 1

development:
  _extends: production
  phpSettings:
    display_startup_errors: 1
    display_errors: 1
  resources:
    frontController:
      params:
        displayExceptions: 1
