basket_add:
  type: Zend_Controller_Router_Route_Static
  route: add_to_basket
  defaults:
    module: basket
    controller: product
    action: add

basket:
  type: Zend_Controller_Router_Route_Static
  route: basket
  defaults:
    module: basket
    controller: index
    action: index

catalog:
  type: Zend_Controller_Router_Route_Static
  route: /
  defaults:
    module: default
    controller: index
    action: index
