parameters:
    customer.session.namespace: customer

services:
  front.product.factory:
    class: "Product\ReadStack\Factory\Doctrine"

  front.product.repository:
    class:  "Product\ReadStack\Repository\Doctrine"
    arguments: ["@front.product.factory"]

  front.product.model.catalog:
    class: "\Default_Model_Catalog"
    arguments: ["@front.product.repository", "@basket.forms.add.builder"]

  basket.forms.add.builder:
    class: "Basket\Form\Add\Builder"

  basket.forms.add.handler:
    class: "Basket\Form\Add\Handler"
    arguments: ["@customer.repository"]

  customer.factory:
    class: "Customer\Factory\SessionIdBased"

  customer.repository:
    class: "Customer\Repository\CurrentSession"
    arguments: ["%customer.session.namespace%", "@customer.factory"]