services:
  front.product.factory:
    class: "Product\ReadStack\Factory\Doctrine"

  front.product.repository:
    class:  "Product\ReadStack\Repository\Doctrine"
    arguments: ["@front.product.factory"]

  basket.forms.add.builder:
    class: "\Basket_Form_Add_Builder"

  basket.forms.add.handler:
    class: "\Basket_Form_Add_Handler"