services:
  front.product.factory:
    class: "Product\ReadStack\Factory\Doctrine"

  front.product.repository:
    class:  "Product\ReadStack\Repository\Doctrine"
    arguments: ["@front.product.factory"]
